### PR TITLE
Implement harvest window

### PR DESCRIPTION
**Pull request by arturino009**
Added harvest window offsets and some basic properties. 
I have no clue how to write this and it is pretty wack, but it shows in Devtree pretty nicely.
Basically added ability to access harvest crafts and their name, level and count.

Properties change upon viewing the crafts, so it's impossible to know the crafts before fighting the monsters.

### CODE REVIEW

**Comment by arturino009** [comment]
Also some crafts are too long and are not read by readstring() function fully. I doubled the size of reading. Now it should work with longer strings.

**Comment by Queuete** [comment]
Sorry for my long response time on that pull request, I actually looked at it earlier but did not comment on it.
The change to the readstring function sadly affects other parts aswell, due to not changing the exact use of that function but the default parameter value. 
I am currently not able if this makes a noticeable difference in performance and if it does I dont think the upside of having the Harvest window crafts available would make up for it, unless there is a highly useful plugin which takes advantage of this data.

**Comment by arturino009** [comment]
So I changed the fork so it wouldn't change the readstring() function. It now uses a function ReadStringLong() which is actually used nowhere. Also added some necessary things to Element.

**Comment by Queuete** [comment]
Perfect, thanks for your contribution and flexibility - Sorry again for the long waiting time.

**Pull request merged**
