### PR TITLE
DelveDarknessElem

### PR DESCRIPTION
**Pull request by wlastas**
nice for auto using a flare

### CODE REVIEW

**Review by Queuete — CHANGES_REQUESTED** [review]
Please stick to the current naming scheme and camelCase instead of snake_case.
-> The class should be called DelveDarknessElement (no reason to save 3 characters there) or only DelveDarkness
-> The FieldOffset got a type. DelveDark**n**ess vs DelveDarkess
-> delve_darkness_elem should be DelveDarkness(Element)

**Comment by wlastas** [comment]
I seem to have corrected everything - sorry

**Review by Queuete — CHANGES_REQUESTED** [review]
If I see this correctly currently 2 files exist:
- DelveDarknessElem.cs
- DelveDarknessElement.cs

Could you please delete the first of those?

Then everything is fine and I am going to merge the changes!

**Comment by wlastas** [comment]
oh sorry again
I have no experience of teamwork through github at all
I deleted the DelveDarknessElem.cs file
I finally thought of installing GitHub Extension for Visual Studio
And I will try to figure out how it works

**Pull request merged**
