### PR TITLE
3.19 Offsets and enum update

### PR DESCRIPTION
**Pull request by snowhawk04**
Mods memory struct introduced a new family field (pointer to key-file pointer pair). 
Stash Tab memory struct increased with more information (assuming trade related info). Struct size is manually set instead of automatically calculated, so needed to update.
Updated enumeration values for Gamestat and Inventory tabs.
Updated the usual offsets from every patch. IngameState, Data, ServerData, and UI Elements. 

Note - UI elements file layout was reverted back to memory layout order to make updating easier. If you want it to be ordered by name, feel free to discard this entire pull request and cherry-pick the updates you want.

### CODE REVIEW

**Comment by snowhawk04** [comment]
Should also note that nothing appears to have changed with 3.19.0d.

Plugins tested include

Advanced Tooltip
Advanced Uber Lab Layout
AutoOpen
BasicFlaskRoutine
DevTree
FullRareSetManager
GemUp
HealthBars
HighlightedItems
IconsBuilder
MinimapIcons
MiscInformation
Pickit
Stashie

**Comment by Queuete** [comment]
Thanks a lot for your time investment and ongoing work.

**Comment by Queuete** [comment]
@snowhawk04 The build failed sadly. Probably there were some changes in there which currently only exist in your repository?

I can clean this up tomorrow afternoon, wont be at my pc before, sorry.

`PrepareForBuild:
  Creating directory "../PoeHelper/".
  Creating directory "obj/Release/net48/".
/buddy/exileapi/Core/Core.csproj : warning NU1603: ExileCore depends on Microsoft.Build (>= 15.1.0) but Microsoft.Build 15.1.0 was not found. An approximate best match of Microsoft.Build 15.1.548 was resolved.
/buddy/exileapi/Core/Core.csproj : warning NU1603: ExileCore depends on Microsoft.Build.Framework (>= 15.1.0) but Microsoft.Build.Framework 15.1.0 was not found. An approximate best match of Microsoft.Build.Framework 15.1.548 was resolved.
Project "/buddy/exileapi/Core/Core.csproj" (1) is building "/buddy/exileapi/GameOffsets/GameOffsets.csproj" (2:2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj/Release/net48/".
CoreCompile:
  /usr/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:4 /define:TRACE;RELEASE;NETFRAMEWORK;NET48 /highentropyva+ /reference:/usr/lib/mono/4.8-api/mscorlib.dll /reference:/root/.nuget/packages/sharpdx/4.2.0/lib/net45/SharpDX.dll /reference:/root/.nuget/packages/sharpdx.mathematics/4.2.0/lib/net45/SharpDX.Mathematics.dll /reference:/usr/lib/mono/4.8-api/System.Core.dll /reference:/usr/lib/mono/4.8-api/System.Data.dll /reference:/usr/lib/mono/4.8-api/System.dll /reference:/usr/lib/mono/4.8-api/System.Drawing.dll /reference:/usr/lib/mono/4.8-api/System.IO.Compression.FileSystem.dll /reference:/usr/lib/mono/4.8-api/System.Numerics.dll /reference:/usr/lib/mono/4.8-api/System.Runtime.Serialization.dll /reference:/usr/lib/mono/4.8-api/System.Xml.dll /reference:/usr/lib/mono/4.8-api/System.Xml.Linq.dll /debug- /debug:pdbonly /filealign:512 /optimize+ /out:obj/Release/net48/GameOff ...
  Using shared compilation with compiler from directory: /usr/lib/mono/msbuild/Current/bin/Roslyn
_CopyFilesMarkedCopyLocal:
  Copying file from "/root/.nuget/packages/sharpdx/4.2.0/lib/net45/SharpDX.dll" to "/buddy/exileapi/PoeHelper/SharpDX.dll".
  Copying file from "/root/.nuget/packages/sharpdx.mathematics/4.2.0/lib/net45/SharpDX.Mathematics.dll" to "/buddy/exileapi/PoeHelper/SharpDX.Mathematics.dll".
  Creating "/buddy/exileapi/GameOffsets/obj/Release/net48/GameOffsets.csproj.CopyComplete" because "AlwaysCreate" was specified.
CopyFilesToOutputDirectory:
  Copying file from "/buddy/exileapi/GameOffsets/obj/Release/net48/GameOffsets.dll" to "/buddy/exileapi/PoeHelper/GameOffsets.dll".
  GameOffsets -> /buddy/exileapi/PoeHelper/GameOffsets.dll
  Copying file from "/buddy/exileapi/GameOffsets/obj/Release/net48/GameOffsets.pdb" to "/buddy/exileapi/PoeHelper/GameOffsets.pdb".
Done Building Project "/buddy/exileapi/GameOffsets/GameOffsets.csproj" (default targets).
CoreCompile:
  /usr/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /unsafe+ /checked- /nowarn:1701,1702,1701,1702 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:4 /define:TRACE;RELEASE;NETFRAMEWORK;NET48 /highentropyva+ /reference:/root/.nuget/packages/antlr4.runtime/4.6.6/lib/net45/Antlr4.Runtime.dll /reference:/buddy/exileapi/PoeHelper/GameOffsets.dll /reference:/root/.nuget/packages/mousekeyhook/5.6.0/lib/net40/Gma.System.MouseKeyHook.dll /reference:/buddy/exileapi/deps/ImGui.NET.dll /reference:/root/.nuget/packages/inlineil.fody/1.3.2/lib/net452/InlineIL.dll /reference:/root/.nuget/packages/linqfaster/1.0.0/lib/net461/JM.LinqFaster.dll /reference:/root/.nuget/packages/libgit2sharp/0.26.2/lib/net46/LibGit2Sharp.dll /reference:/root/.nuget/packages/microsoft.build/15.1.548/lib/net46/Microsoft.Build.dll /reference:/root/.nuget/packages/microsoft.build.framework/15.1.548/lib/net46/Microsoft.Build.Framework.dll /reference:/root/.nuget/packages/microsoft.codedom.providers.dotnet ...
  Using shared compilation with compiler from directory: /usr/lib/mono/msbuild/Current/bin/Roslyn
/buddy/exileapi/Core/PoEMemory/MemoryObjects/IngameUIElements.cs(93,106): error CS1061: 'IngameUElementsOffsets' does not contain a definition for 'SynthesisWindow' and no accessible extension method 'SynthesisWindow' accepting a first argument of type 'IngameUElementsOffsets' could be found (are you missing a using directive or an assembly reference?) [/buddy/exileapi/Core/Core.csproj]
/buddy/exileapi/Core/PoEMemory/MemoryObjects/IngameUIElements.cs(113,121): error CS1061: 'IngameUElementsOffsets' does not contain a definition for 'HorticraftingSacredGrovePanel' and no accessible extension method 'HorticraftingSacredGrovePanel' accepting a first argument of type 'IngameUElementsOffsets' could be found (are you missing a using directive or an assembly reference?) [/buddy/exileapi/Core/Core.csproj]
/buddy/exileapi/Core/Shared/PluginManager.cs(64,13): warning CS0618: 'EntityListWrapper.EntityAddedAny' is obsolete: 'Use 'EntityAdded' instead. Going to be removed in 3.15' [/buddy/exileapi/Core/Core.csproj]
/buddy/exileapi/Core/Shared/PluginManager.cs(65,13): warning CS0618: 'EntityListWrapper.EntityIgnored' is obsolete: 'Going to be removed in 3.15' [/buddy/exileapi/Core/Core.csproj]
/buddy/exileapi/Core/Shared/PluginManager.cs(229,45): warning CS0618: 'IngameState.ServerData' is obsolete: 'InGameState.ServerData has been relocated to InGameState.IngameData.ServerData in patch 3.16.' [/buddy/exileapi/Core/Core.csproj]
/buddy/exileapi/Core/EntityListWrapper.cs(35,37): warning CS0067: The event 'EntityListWrapper.EntityIgnored' is never used [/buddy/exileapi/Core/Core.csproj]
/buddy/exileapi/Core/EntityListWrapper.cs(33,37): warning CS0067: The event 'EntityListWrapper.EntityAddedAny' is never used [/buddy/exileapi/Core/Core.csproj]
Done Building Project "/buddy/exileapi/Core/Core.csproj" (default targets) -- FAILED.

Build FAILED.

"/buddy/exileapi/Core/Core.csproj" (default target) (1) ->
(ResolvePackageAssets target) -> 
  /buddy/exileapi/Core/Core.csproj : warning NU1603: ExileCore depends on Microsoft.Build (>= 15.1.0) but Microsoft.Build 15.1.0 was not found. An approximate best match of Microsoft.Build 15.1.548 was resolved.
  /buddy/exileapi/Core/Core.csproj : warning NU1603: ExileCore depends on Microsoft.Build.Framework (>= 15.1.0) but Microsoft.Build.Framework 15.1.0 was not found. An approximate best match of Microsoft.Build.Framework 15.1.548 was resolved.


"/buddy/exileapi/Core/Core.csproj" (default target) (1) ->
(CoreCompile target) -> 
  /buddy/exileapi/Core/Shared/PluginManager.cs(64,13): warning CS0618: 'EntityListWrapper.EntityAddedAny' is obsolete: 'Use 'EntityAdded' instead. Going to be removed in 3.15' [/buddy/exileapi/Core/Core.csproj]
  /buddy/exileapi/Core/Shared/PluginManager.cs(65,13): warning CS0618: 'EntityListWrapper.EntityIgnored' is obsolete: 'Going to be removed in 3.15' [/buddy/exileapi/Core/Core.csproj]
  /buddy/exileapi/Core/Shared/PluginManager.cs(229,45): warning CS0618: 'IngameState.ServerData' is obsolete: 'InGameState.ServerData has been relocated to InGameState.IngameData.ServerData in patch 3.16.' [/buddy/exileapi/Core/Core.csproj]
  /buddy/exileapi/Core/EntityListWrapper.cs(35,37): warning CS0067: The event 'EntityListWrapper.EntityIgnored' is never used [/buddy/exileapi/Core/Core.csproj]
  /buddy/exileapi/Core/EntityListWrapper.cs(33,37): warning CS0067: The event 'EntityListWrapper.EntityAddedAny' is never used [/buddy/exileapi/Core/Core.csproj]


"/buddy/exileapi/Core/Core.csproj" (default target) (1) ->
(CoreCompile target) -> 
  /buddy/exileapi/Core/PoEMemory/MemoryObjects/IngameUIElements.cs(93,106): error CS1061: 'IngameUElementsOffsets' does not contain a definition for 'SynthesisWindow' and no accessible extension method 'SynthesisWindow' accepting a first argument of type 'IngameUElementsOffsets' could be found (are you missing a using directive or an assembly reference?) [/buddy/exileapi/Core/Core.csproj]
  /buddy/exileapi/Core/PoEMemory/MemoryObjects/IngameUIElements.cs(113,121): error CS1061: 'IngameUElementsOffsets' does not contain a definition for 'HorticraftingSacredGrovePanel' and no accessible extension method 'HorticraftingSacredGrovePanel' accepting a first argument of type 'IngameUElementsOffsets' could be found (are you missing a using directive or an assembly reference?) [/buddy/exileapi/Core/Core.csproj]

    7 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.22
Action failed: see logs above for details`

**Comment by snowhawk04** [comment]
Yea, already saw that. Sent a fix for the missing definitions as they were removed from the UI elements memory layout. I just didn't  cherry pick that specific pull.

**Pull request merged**
