### PR TITLE
on/off using SoundController on same VM fix

### PR DESCRIPTION
**Pull request by wlastas**

### CODE REVIEW

**Comment by wlastas** [comment]
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/933093-exileapi-3-13-release-40.html#post4299587
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/923930-poehud-plugin-follower-17.html#post4298410

**Comment by Queuete** [comment]
This does not really fix the underlying issue. Every useage of the SoundController (every plugin which uses it) would simply fail.

**Comment by wlastas** [comment]
So I do not suggest deleting it - those who need it will simply turn it on in the settings, and in the plugin code they will add a check for the controller equal to null.
It's just that 2 users were unable to start poehelper on the VM due to this error, and obviously they cannot recompile Core.dll on their own.
Sharing an audio adapter to a virtual machine leads to bugs with sound (freezes and trills)

**Comment by Queuete** [comment]
Done in latest commit, a setting (especially with default false) seems to be not the right choice for this.
It now logs an error when the SoundCOntroller fails, but the api will start either way.

**Pull request closed without merging**
