### PR TITLE
Update IngameDataOffsets.cs 3.17.3

### PR DESCRIPTION
**Pull request by wlastas**

### CODE REVIEW

**Comment by HugKitten** [comment]
Sorry bud. I already got to it first. :P

**Comment by HugKitten** [comment]
Although interesting enough, your fix updates IngameDataOffsets's Terrain while mines changes the TerrainData's offsets. Merging this would actually break things again.

**Comment by HugKitten** [comment]
Just checked Cheat Engine's find out what accesses this address list. I'll try to follow the offsets being used by OP codes in the future. Updated my repo to follow this standard.

**Comment by Queuete** [comment]
> Sorry bud. I already got to it first. :P

Actually wlastas Terrain changes were here earlier, but there was also a (probably uncomplete?) class name change: TerrainData Terrain -> TerrainStruct Terrain

Otherwise I would have merged this request, but I would expect that this change would have let to a compile error.

Anyway, thanks to both of you for your work!

**Comment by HugKitten** [comment]
My bad! Sorry to stealing your thunder then. :P

**Pull request closed without merging**
