### PR TITLE
Update Element.cs

### PR DESCRIPTION
**Pull request by wlastas**
three new convenient recursive methods for working with text elements

### CODE REVIEW

**Review by Queuete — COMMENTED** [review]
Hello there,

Thanks for your contribution.
Is there any specific reasons why your methods expect a ref parameter instead of returning a value?
In general if I call a Get... method I would expect a return value.

Best Regards

**Comment by wlastas** [comment]
> Is there any specific reasons why your methods expect a ref parameter instead of returning a value?
> In general if I call a Get... method I would expect a return value.
hi
hm, here's a recursive call which searches for an element in an unlimited number of tree nestings & I can only use it like this:
 public Element play_btn {
            get {
                Element btn = null;
                GetChildFromIndices(0,0,1,3)?.GetElementByString("play", ref btn);
                return btn?.Parent;
            }
        }
       do you know how to do it without ref ? Can i see>?

**Comment by wlastas** [comment]
Live and learn
I like your method better.
With your permission, I will add it to my piggy bank^^

**Comment by Queuete** [comment]
Sure do that. Code snippets I post in this repository (including issues and pull request) can be considered open source and you can do with them whatever you want. ;)
Are you planning to apply those changes to this pull request?

**Comment by wlastas** [comment]
I replaced it with the option you proposed without ref

**Comment by Queuete** [comment]
You pushed your changes to your master branch, so it ended up in your other pull request.
This Pull request references a "patch-1" branch in your repository (maybe auto generated?). 
Gonna close this one, the changes are already merged. ;)

**Pull request closed without merging**
